### ISSUE TITLE
Tick not being incremented correctly

### ISSUE THREAD

**Issue by Tirre** [SzymonLisowiec/node-CSGODemoReader#1]
Hi, I've noticed that the Tick variable is not being updated properly and is sent as 0 in to all events.
This is something that worked with @mikeemoo JSGO version and that I am missing in this.

From the troubleshooting I've done, the handling of ticks doesn't seem to have changed and I have been unable to find the faulty handling.
Didn't know how else to contact you except by submitting an issue.

Could you take a look at it?

**Comment by SzymonLisowiec** [comment]
Hello,
The bug has been fixed.

**Comment by Tirre** [comment]
Cheers mate, appreciated for the quick fix and response!
