### ISSUE TITLE
Few bugs in the Player methods

### ISSUE THREAD

**Issue by Tirre** [SzymonLisowiec/node-CSGODemoReader#2]
Method getEyeAngle() is attempting to call non-defined function "makeAnglePositive()".
Method getEyeAngleVector() is attempting to call non-defined function "directionToVector()".
Method hasHelmet() is attempting to read the attribute "m_bHasFelmet" which should be "m_bHasHelmet".

Some methods also attempt to return Vector3d or Line3d objects which are also breaking.

"csgodemoreader/src/Entities/Player.js:80
                        return new Vector3d(xy.x, xy.y, z);
                        ^
ReferenceError: Vector3d is not defined"

Believe these are objects from third-party libraries that are not properly imported?

These are some things that I found that you might want to fix.
Really appreciate this project 👍

**Comment by SzymonLisowiec** [comment]
Hi,
Thanks for report bugs. These are forgotten methods from original jsgo. I will fix it in the near future.

**Comment by caio1985** [comment]
hi Szymon, wondering if you had the chance to implement these methods. Thanks!

**Comment by SzymonLisowiec** [comment]
Fixed in https://github.com/SzymonLisowiec/node-CSGODemoReader/commit/458bdcf6f456206dddcd5c7d3e02c7c4965ba88b Please update library to version `1.0.22`. Thanks guys ❤
