### ISSUE TITLE
demo.getRound() and bug with emitting 'end' events

### ISSUE THREAD

**Issue by Tirre** [SzymonLisowiec/node-CSGODemoReader#3]
I have found at least two other bugs that I'd like to report:

The variable exposed through demo.getRound() doesn't get incremented correctly as rounds can be restarted (triggering multiple csgo.round_start events).
This causes the demo.getRound() to not show the correct current round.
This can be fixed by looping through the teams, fetching the score and adding 1.

Also, I have had at least one demo where the 'end' event never was sent, leading to the demo-parser getting stuck and having to manually exit the application.
This can also be fixed by checking for the return value of let command = this.stream.byte() on line 65 in Reader.js and emit the 'end' event if undefined is returned.

**Comment by SzymonLisowiec** [comment]
Fixed in pull request https://github.com/SzymonLisowiec/node-CSGODemoReader/pull/4 and these fixes are published as `csgodemoreader@1.0.21`.
